name: Label issues
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  triage_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Label issues
        uses: andymckay/labeler@1.0.2
        with:
          add-labels: 'triage'