name: Move and unlabel ready to merge issues
on:
  issues:
    types:
      - labeled

jobs:
  unmark_for_review:
    if: github.repository == 'apm-pub-org/apm-pub-org-pub-repo' && github.event.label.name == 'ready to merge'
    runs-on: ubuntu-latest
    steps:
      - name: move issue
        uses: alex-page/github-project-automation-plus@fdb7991b72040d611e1123d2b75ff10eda9372c9
        with:
          project: apm-org-repo-board
          column: c1
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: remove label
        uses: andymckay/labeler@22d5392de2b725cea4b284df5824125054049d84
        with:
          remove-labels: "waiting for review"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
