name: Move ready to merge issues
on:
  issues:
    types:
      - labeled
jobs:
  remove_labels:
#     if: github.event.project_card.column_id == '13186353'
    runs-on: ubuntu-latest
    steps:
      - name: remove labels
        uses: andymckay/labeler@master
        with:
          remove-labels: "bug"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
